import Head from 'next/head';
import Header from '../components/Header';


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     {/* Header */}
        <Header/>
     <main>
       {/* Sidebar */}
       {/* Feed */}
       {/* Widgets */}
     </main>
    </div>
  )
}
