import Head from 'next/head';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';


export default function Home() {
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     {/* Header */}
        <Header/>
     <main className = "flex">
       {/* Sidebar */}
         <Sidebar/>
       {/* Feed */}
        <Feed/>
       {/* Widgets */}
     </main>
    </div>
  );
}
